audit_header: false
title: East Valley Real Estate Video Blog with Hani Aldulaimi
description: Our mission at Commercial Infinity Group is to be your best resource for East Valley real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The Commercial Infinity Group, your professional East Valley Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:

client:
  name: Hani Aldulaimi
  title:
  license_number:
  about_markdown: |
    Raised in New York and a graduate of Cornell University, Hani Aldulaimi has been living and focusing on Real Estate in Arizona for over ten years. While working with Chevron Corporation, Hani was involved in new business acquisitions, asset management, and real estate development of service stations and retail centers in the Phoenix, Tucson, Las Vegas and Southern California markets.
  market: East Valley
  brand: Commercial Infinity Group
  brokerage: Keller Williams
  address: 2077 E. Warner Rd., Suite 110<br>Tempe, AZ 85284
  phone: 480-900-8484
  phone_type:
  phone2:
  phone2_type:
  email: info@kwcig.com
  url: http://www.kwcig.com

CTAs:
  first_CTA_text: Needs Analysis
  first_CTA_URL: http://www.commercialinfinitygroup.com/needs-analysis/
  second_CTA_text: Contact Us
  second_CTA_URL: http://www.commercialinfinitygroup.com/contact-us/

sidebar_CTA:
  - CTA_image_path: /img/cta-images/004.jpg
    CTA_title: "What are the most important factors you want in a commercial space?"
    CTA_text: "There is a lot to consider when buying, selling or leasing a Commercial Real Estate property. Choosing the right location, the right neighborhood, the perfect layout - it can become overwhelming."
    CTA_link_text: "Needs Analysis"
    CTA_url: http://www.commercialinfinitygroup.com/needs-analysis/

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/006.jpg
    CTA_title2: "How can we help you?"
    CTA_text2: "If you’d like to talk to us about a project, or anything else, we’d love to hear from you."
    CTA_link_text2: "Contact Us"
    CTA_url2: http://www.commercialinfinitygroup.com/contact-us/

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/KWCIG/
  linkedin_url:
  gplus_url:
  youtube_url:
  twitter_url: https://twitter.com/kwcig
  instagram_url: https://www.instagram.com/kwcommercialinfinitygroup/
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: 'East Valley Real Estate Podcast with Hani Aldulaimi'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the East Valley Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from Commercial Infinity Group - your professional East Valley Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in East Valley, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Hani Aldulaimi'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 60
  hero_text: East Valley Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#b32025'
  theme_color: '#999'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: black

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
